CREATE TABLE WtoData_Export(
  IndicatorCategory VARCHAR(100),
  IndicatorCode VARCHAR(10),
  Indicator VARCHAR(1000),
  ReportingEconomyCode VARCHAR(10),
  ReportingEconomyISO3ACode VARCHAR(10),
  ReportingEconomy VARCHAR(100),
  PartnerEconomyCode VARCHAR(10),
  PartnerEconomyISO3ACode VARCHAR(10),
  PartnerEconomy VARCHAR(100),
  ProductSectorClassificationCode VARCHAR(10),
  ProductSectorClassification VARCHAR(100),
  ProductSectorCode VARCHAR(10),
  ProductSector VARCHAR(100),
  PeriodCode VARCHAR(10),
  Period VARCHAR(100),
  FrequencyCode VARCHAR(10),
  Frequency VARCHAR(100),
  UnitCode VARCHAR(10),
  Unit VARCHAR(100),
  Year INT,
  ValueFlagCode VARCHAR(10),
  ValueFlag VARCHAR(100),
  TextValue VARCHAR(100),
  Value DECIMAL(20,3)
);
